version: '3.7'
services:
  app:
    working_dir: /app
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - ./:/app
    command: bash -c './gradlew bootRun'
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - findmycar

  postgresdb:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: findmycar
    ports:
      - 5432:5432
    networks:
      - findmycar

networks:
  findmycar:
