spring:
  datasource:
    url: jdbc:mysql://localhost:3306/findmycar?createDatabaseIfNotExist=true&useSSL=false
    username: root

  flyway:
    user: root
    locations: classpath:/db/migration

  jpa:
    show-sql: true
